name: ros-markers-james
version: '1.0'
grade: stable
confinement: strict
summary: ROS App Snap
description: Shows how to use visualization markers to send basic shapes
passthrough:
  base: core18-ros-james

apps:
  ui:
    command: run-viz
    plugs: [network, network-bind, unity7, opengl]
  launch-project:
    command: run-system
    plugs: [network, network-bind, unity7, opengl]

parts:
  ros-app:
    plugin: catkin
    rosdistro: kinetic
    include-roscore: false
    underlay:
      # Build-time location of the underlay
      build-path: $SNAPCRAFT_PART_INSTALL/opt/ros/kinetic

      # Run-time location of the underlay
      run-path: /opt/ros/kinetic
    catkin-packages:
      - visualization_marker_tutorials
    stage-packages:
      - xcb
      - rviz
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
    build-packages:
      - libc6
    after:
      - desktop-qt5

  run-system:
    plugin: dump
    stage:
      - bin/run-system
      - bin/run-viz
    prime: 
      - bin/run-system
      - bin/run-viz
